import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  ladoalado: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginVertical: 10,
  },
  areaInterna: {
    flex: 1,
  },

  botao1: {
    backgroundColor: "#00a849ff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  botao2: {
    backgroundColor: "#44f9ff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  botao3: {
    backgroundColor: "#355e75ff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  botao4: {
    backgroundColor: "#d37b17ff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  botao5: {
    backgroundColor: "#552d57ff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  botao6: {
    backgroundColor: "#ffff6cff",
    width: 160,
    height: 60,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },

  caixaTexto: {
    backgroundColor: "#222",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "85%",
  },
  textoCor: {
    color: "#fff",
    fontSize: 16,
    marginBottom: 6,
    textAlign: "center",
  },
  botaoLimpar: {
    backgroundColor: "red",
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 6,
    marginTop: 6,
  },
});
